// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3ITuhtjwBHQsJjCUfZEW0vtUUimbvXXk',
    appId: '1:905902503743:web:98b346d6d1a44e4ebc458a',
    messagingSenderId: '905902503743',
    projectId: 'dijinx-check-app',
    authDomain: 'dijinx-check-app.firebaseapp.com',
    storageBucket: 'dijinx-check-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1FKjqiIBohp6bXWm8NRbJQNCKJ4uppeQ',
    appId: '1:905902503743:android:5cfbb73593e22a0cbc458a',
    messagingSenderId: '905902503743',
    projectId: 'dijinx-check-app',
    storageBucket: 'dijinx-check-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiKkYLX3mqaEam5dirNs6Y3J8-b61aMW8',
    appId: '1:905902503743:ios:bb681b2d89c6dfcfbc458a',
    messagingSenderId: '905902503743',
    projectId: 'dijinx-check-app',
    storageBucket: 'dijinx-check-app.appspot.com',
    iosClientId: '905902503743-foj6unipncr4pgatrb8fnt81mdethhsb.apps.googleusercontent.com',
    iosBundleId: 'com.dijinx.checkApp',
  );
}